spring.application.name=CalculadoraHuellaCarbono

# 1. Ruta de la Base de Datos (Se creará o buscará en la carpeta resources)
spring.datasource.url=jdbc:sqlite:src/main/resources/proyectoPOO.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 3. Comportamiento de la BD (update mantiene tus datos y añade lo nuevo)
spring.jpa.hibernate.ddl-auto=update

# 4. (Opcional) Muestra en la consola de Java las consultas SQL que se están ejecutando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.orm.jdbc.bind=trace

# Configuración para JWT
security.jwt.secret=dslfjdladJKLKJKgfd
security.jwt.issuer=CalculadoraHuellaCarbono
# Expiración del token en milisegundos (7 días)
security.jwt.ttlMillis=604800000